"""Initial schema

Revision ID: 72147ce4c0a5
Revises: 
Create Date: 2026-01-15 09:11:39.318826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72147ce4c0a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('microsoft_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_microsoft_user_id'), 'users', ['microsoft_user_id'], unique=True)
    op.create_table('detection_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('detection_count', sa.Integer(), nullable=True),
    sa.Column('violation_count', sa.Integer(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detection_history_timestamp', 'detection_history', ['timestamp'], unique=False)
    op.create_index('idx_detection_history_user_timestamp', 'detection_history', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_detection_history_timestamp'), 'detection_history', ['timestamp'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_timestamp_location', 'reports', ['timestamp', 'location'], unique=False)
    op.create_index('idx_reports_user_timestamp', 'reports', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_reports_location'), 'reports', ['location'], unique=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_reports_timestamp'), 'reports', ['timestamp'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('violation_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('osha_standard', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_violations_location_timestamp', 'violations', ['location', 'timestamp'], unique=False)
    op.create_index('idx_violations_report', 'violations', ['report_id'], unique=False)
    op.create_index('idx_violations_type_timestamp', 'violations', ['violation_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_violations_location'), 'violations', ['location'], unique=False)
    op.create_index(op.f('ix_violations_timestamp'), 'violations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_violations_violation_type'), 'violations', ['violation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_violation_type'), table_name='violations')
    op.drop_index(op.f('ix_violations_timestamp'), table_name='violations')
    op.drop_index(op.f('ix_violations_location'), table_name='violations')
    op.drop_index('idx_violations_type_timestamp', table_name='violations')
    op.drop_index('idx_violations_report', table_name='violations')
    op.drop_index('idx_violations_location_timestamp', table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_reports_timestamp'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_location'), table_name='reports')
    op.drop_index('idx_reports_user_timestamp', table_name='reports')
    op.drop_index('idx_reports_timestamp_location', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_detection_history_timestamp'), table_name='detection_history')
    op.drop_index('idx_detection_history_user_timestamp', table_name='detection_history')
    op.drop_index('idx_detection_history_timestamp', table_name='detection_history')
    op.drop_table('detection_history')
    op.drop_index(op.f('ix_users_microsoft_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
